name: Java CI with Gradle on DEV

# develop 브랜치에 pull_request 시에 동작
on:
  pull_request:
    branches: [ "develop" ]

permissions:
  contents: read

# 동작 과정
jobs:
  build:
    
    # ubuntu 최신 버전에서 작동
    runs-on: ubuntu-latest

    steps:
    # 1) 워크플로우 실행 전 기본적으로 체크아웃 필요
    - name: checkout
      uses: actions/checkout@v3
    
    # 2) JDK 11버전 설치, 다른 JDK 버전을 사용하다면 수정
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    
    # 3) 환경변수 파일 생성
    - name: application.yml 파일 생성
      run: |
        ## create application-dev.yml
        cd ./lionheart-api/src/main/resources/
        
        # 프로퍼티 파일 생성
        touch ./application-dev.yml
        
        # Github-Secrets에 설정한 값을 프로퍼티 파일에 씌우기
        echo "${{ secrets.DEV_APPLICATION }}" >> ./application-dev.yml
        
        # 프로퍼티 파일 확인
        cat ./application-dev.yml
      shell: bash
      
    # 이 워크플로우는 gradle build
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    
    - name: Build with Gradle # 실제 application build(-x 옵션을 통해 테스트는 제외)
      run: ./gradlew clean build -x test
        
    
