name: Notification Server Java CI with Gradle on DEV

# develop 브랜치에 pull_request 시에 동작
on:
  pull_request:
    branches: [ "develop" ]
    paths:
      - lionheart-notification/**
      - lionheart-domain/**
      - lionheart-common/**
      - lionheart-external/**

permissions:
  contents: read

# 동작 과정
jobs:
  build:
    
    # ubuntu 최신 버전에서 작동
    runs-on: ubuntu-latest

    steps:
      # 1) 워크플로우 실행 전 기본적으로 체크아웃 필요
      - name: checkout
        uses: actions/checkout@v3

      # 2) JDK 11버전 설치, 다른 JDK 버전을 사용하다면 수정
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      # 3) AWS Secrets Manger 환경변수 사용
      - name: Read secrets from AWS Secrets Manager into environment variables
        uses: abhilash1in/aws-secrets-manager-action@v1.1.0
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_DEV }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY_DEV }}
          aws-region: ap-northeast-2
          secrets: /secret/lionheart-dev
          parse-json: false

      # 4) Firebase secret 파일 생성
      - name: create firebase secret file
        working-directory: ./lionheart-notification/src/main/resources
        run: |
          mkdir firebase
          touch ./firebase/firebase_service_key.json
          echo "${{ secrets.FIREBASE_SERVICE_KEY_JSON }}" >> ./firebase/firebase_service_key.json
          sed -i 's/#/"/g' ./firebase/firebase_service_key.json
      
      # build
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle # 실제 application build(-x 옵션을 통해 테스트는 제외)
        run: ./gradlew lionheart-notification:bootJar -x test
        
    
